import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-retirement-plan-forfeiture-allocation-compliance",
  "engine": "recovery",
  "title": "Retirement Plan Forfeiture Allocation Compliance",
  "shortTitle": "Retirement Plan Forfeiture Allocation Compliance",
  "tagline": "Ensure forfeitures are recognized timely and used only for plan-authorized contributions, expenses, or participant allocations.",
  "industry": "Retirement Plan Operations",
  "buyer": "401(k) plan sponsors and recordkeepers",
  "uiPort": 4676,
  "apiPort": 5676,
  "accent": "#b45309",
  "currency": "USD",
  "primaryOutcome": "Retirement Plan Forfeiture Allocation Compliance converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect plan documents, participant balances, vesting, terminations, forfeitures, employer contributions, expenses, correction rules, allocations, and filings in one accountable workflow. Ensure forfeitures are recognized timely and used only for plan-authorized contributions, expenses, or participant allocations.",
  "calculation": {
    "actualKey": "receivedAmount",
    "expectedKey": "entitledAmount",
    "actualLabel": "Received or Recognized Amount",
    "expectedLabel": "Contract or Rule-Supported Entitlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Retirement Plan Forfeiture Allocation Compliance evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("plan-document-rules","RPF01","Plan document rules","Execute plan document rules using plan documents, participant balances, vesting, terminations, forfeitures, employer contributions, expenses, correction rules, allocations, and filings.","Produce a governed plan document rules decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Plan / Forfeiture Account","text","Plan / Forfeiture Account · Standard Case"],["caseReference","Plan document rules Reference","text","RPF01-2026-001"],["receivedAmount","Received or Recognized Amount","currency",961250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1163113],["domainDriver","Permitted Use","select","Reduce contributions",["Reduce contributions","Pay expenses","Reallocate to participants"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Plan document rules case","Participant vesting ingestion case","Termination event control case","Forfeiture recognition case","Restoration obligation case"]}),
feature("participant-vesting-ingestion","RPF02","Participant vesting ingestion","Execute participant vesting ingestion using plan documents, participant balances, vesting, terminations, forfeitures, employer contributions, expenses, correction rules, allocations, and filings.","Produce a governed participant vesting ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Plan / Forfeiture Account","text","Plan / Forfeiture Account · Standard Case"],["caseReference","Participant vesting ingestion Reference","text","RPF02-2026-001"],["receivedAmount","Received or Recognized Amount","currency",961250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1163113],["domainDriver","Permitted Use","select","Reduce contributions",["Reduce contributions","Pay expenses","Reallocate to participants"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Plan document rules case","Participant vesting ingestion case","Termination event control case","Forfeiture recognition case","Restoration obligation case"]}),
feature("termination-event-control","RPF03","Termination event control","Execute termination event control using plan documents, participant balances, vesting, terminations, forfeitures, employer contributions, expenses, correction rules, allocations, and filings.","Produce a governed termination event control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Plan / Forfeiture Account","text","Plan / Forfeiture Account · Standard Case"],["caseReference","Termination event control Reference","text","RPF03-2026-001"],["receivedAmount","Received or Recognized Amount","currency",961250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1163113],["domainDriver","Permitted Use","select","Reduce contributions",["Reduce contributions","Pay expenses","Reallocate to participants"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Plan document rules case","Participant vesting ingestion case","Termination event control case","Forfeiture recognition case","Restoration obligation case"]}),
feature("forfeiture-recognition","RPF04","Forfeiture recognition","Execute forfeiture recognition using plan documents, participant balances, vesting, terminations, forfeitures, employer contributions, expenses, correction rules, allocations, and filings.","Produce a governed forfeiture recognition decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Plan / Forfeiture Account","text","Plan / Forfeiture Account · Standard Case"],["caseReference","Forfeiture recognition Reference","text","RPF04-2026-001"],["receivedAmount","Received or Recognized Amount","currency",961250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1163113],["domainDriver","Permitted Use","select","Reduce contributions",["Reduce contributions","Pay expenses","Reallocate to participants"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Plan document rules case","Participant vesting ingestion case","Termination event control case","Forfeiture recognition case","Restoration obligation case"]}),
feature("restoration-obligation","RPF05","Restoration obligation","Execute restoration obligation using plan documents, participant balances, vesting, terminations, forfeitures, employer contributions, expenses, correction rules, allocations, and filings.","Produce a governed restoration obligation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Plan / Forfeiture Account","text","Plan / Forfeiture Account · Standard Case"],["caseReference","Restoration obligation Reference","text","RPF05-2026-001"],["receivedAmount","Received or Recognized Amount","currency",961250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1163113],["domainDriver","Permitted Use","select","Reduce contributions",["Reduce contributions","Pay expenses","Reallocate to participants"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Plan document rules case","Participant vesting ingestion case","Termination event control case","Forfeiture recognition case","Restoration obligation case"]}),
feature("forfeiture-account-ledger","RPF06","Forfeiture account ledger","Execute forfeiture account ledger using plan documents, participant balances, vesting, terminations, forfeitures, employer contributions, expenses, correction rules, allocations, and filings.","Produce a governed forfeiture account ledger decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Plan / Forfeiture Account","text","Plan / Forfeiture Account · Standard Case"],["caseReference","Forfeiture account ledger Reference","text","RPF06-2026-001"],["receivedAmount","Received or Recognized Amount","currency",961250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1163113],["domainDriver","Permitted Use","select","Reduce contributions",["Reduce contributions","Pay expenses","Reallocate to participants"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Plan document rules case","Participant vesting ingestion case","Termination event control case","Forfeiture recognition case","Restoration obligation case"]}),
feature("permitted-use-validation","RPF07","Permitted use validation","Execute permitted use validation using plan documents, participant balances, vesting, terminations, forfeitures, employer contributions, expenses, correction rules, allocations, and filings.","Produce a governed permitted use validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Plan / Forfeiture Account","text","Plan / Forfeiture Account · Standard Case"],["caseReference","Permitted use validation Reference","text","RPF07-2026-001"],["receivedAmount","Received or Recognized Amount","currency",961250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1163113],["domainDriver","Permitted Use","select","Reduce contributions",["Reduce contributions","Pay expenses","Reallocate to participants"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Plan document rules case","Participant vesting ingestion case","Termination event control case","Forfeiture recognition case","Restoration obligation case"]}),
feature("contribution-offset-calculation","RPF08","Contribution offset calculation","Execute contribution offset calculation using plan documents, participant balances, vesting, terminations, forfeitures, employer contributions, expenses, correction rules, allocations, and filings.","Produce a governed contribution offset calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Plan / Forfeiture Account","text","Plan / Forfeiture Account · Standard Case"],["caseReference","Contribution offset calculation Reference","text","RPF08-2026-001"],["receivedAmount","Received or Recognized Amount","currency",961250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1163113],["domainDriver","Permitted Use","select","Reduce contributions",["Reduce contributions","Pay expenses","Reallocate to participants"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Plan document rules case","Participant vesting ingestion case","Termination event control case","Forfeiture recognition case","Restoration obligation case"]}),
feature("plan-expense-payment-review","RPF09","Plan expense payment review","Execute plan expense payment review using plan documents, participant balances, vesting, terminations, forfeitures, employer contributions, expenses, correction rules, allocations, and filings.","Produce a governed plan expense payment review decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Plan / Forfeiture Account","text","Plan / Forfeiture Account · Standard Case"],["caseReference","Plan expense payment review Reference","text","RPF09-2026-001"],["receivedAmount","Received or Recognized Amount","currency",961250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1163113],["domainDriver","Permitted Use","select","Reduce contributions",["Reduce contributions","Pay expenses","Reallocate to participants"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Plan document rules case","Participant vesting ingestion case","Termination event control case","Forfeiture recognition case","Restoration obligation case"]}),
feature("participant-reallocation","RPF10","Participant reallocation","Execute participant reallocation using plan documents, participant balances, vesting, terminations, forfeitures, employer contributions, expenses, correction rules, allocations, and filings.","Produce a governed participant reallocation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Plan / Forfeiture Account","text","Plan / Forfeiture Account · Standard Case"],["caseReference","Participant reallocation Reference","text","RPF10-2026-001"],["receivedAmount","Received or Recognized Amount","currency",961250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1163113],["domainDriver","Permitted Use","select","Reduce contributions",["Reduce contributions","Pay expenses","Reallocate to participants"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Plan document rules case","Participant vesting ingestion case","Termination event control case","Forfeiture recognition case","Restoration obligation case"]}),
feature("year-end-deadline-monitoring","RPF11","Year-end deadline monitoring","Execute year-end deadline monitoring using plan documents, participant balances, vesting, terminations, forfeitures, employer contributions, expenses, correction rules, allocations, and filings.","Produce a governed year-end deadline monitoring decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Plan / Forfeiture Account","text","Plan / Forfeiture Account · Standard Case"],["caseReference","Year-end deadline monitoring Reference","text","RPF11-2026-001"],["receivedAmount","Received or Recognized Amount","currency",961250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1163113],["domainDriver","Permitted Use","select","Reduce contributions",["Reduce contributions","Pay expenses","Reallocate to participants"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Plan document rules case","Participant vesting ingestion case","Termination event control case","Forfeiture recognition case","Restoration obligation case"]}),
feature("operational-failure-detection","RPF12","Operational failure detection","Execute operational failure detection using plan documents, participant balances, vesting, terminations, forfeitures, employer contributions, expenses, correction rules, allocations, and filings.","Produce a governed operational failure detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Plan / Forfeiture Account","text","Plan / Forfeiture Account · Standard Case"],["caseReference","Operational failure detection Reference","text","RPF12-2026-001"],["receivedAmount","Received or Recognized Amount","currency",961250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1163113],["domainDriver","Permitted Use","select","Reduce contributions",["Reduce contributions","Pay expenses","Reallocate to participants"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Plan document rules case","Participant vesting ingestion case","Termination event control case","Forfeiture recognition case","Restoration obligation case"]}),
feature("correction-calculation","RPF13","Correction calculation","Execute correction calculation using plan documents, participant balances, vesting, terminations, forfeitures, employer contributions, expenses, correction rules, allocations, and filings.","Produce a governed correction calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Plan / Forfeiture Account","text","Plan / Forfeiture Account · Standard Case"],["caseReference","Correction calculation Reference","text","RPF13-2026-001"],["receivedAmount","Received or Recognized Amount","currency",961250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1163113],["domainDriver","Permitted Use","select","Reduce contributions",["Reduce contributions","Pay expenses","Reallocate to participants"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Plan document rules case","Participant vesting ingestion case","Termination event control case","Forfeiture recognition case","Restoration obligation case"]}),
feature("audit-evidence-package","RPF14","Audit evidence package","Execute audit evidence package using plan documents, participant balances, vesting, terminations, forfeitures, employer contributions, expenses, correction rules, allocations, and filings.","Produce a governed audit evidence package decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Plan / Forfeiture Account","text","Plan / Forfeiture Account · Standard Case"],["caseReference","Audit evidence package Reference","text","RPF14-2026-001"],["receivedAmount","Received or Recognized Amount","currency",961250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1163113],["domainDriver","Permitted Use","select","Reduce contributions",["Reduce contributions","Pay expenses","Reallocate to participants"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Plan document rules case","Participant vesting ingestion case","Termination event control case","Forfeiture recognition case","Restoration obligation case"]}),
feature("plan-forfeiture-analytics","RPF15","Plan forfeiture analytics","Execute plan forfeiture analytics using plan documents, participant balances, vesting, terminations, forfeitures, employer contributions, expenses, correction rules, allocations, and filings.","Produce a governed plan forfeiture analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Plan / Forfeiture Account","text","Plan / Forfeiture Account · Standard Case"],["caseReference","Plan forfeiture analytics Reference","text","RPF15-2026-001"],["receivedAmount","Received or Recognized Amount","currency",961250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1163113],["domainDriver","Permitted Use","select","Reduce contributions",["Reduce contributions","Pay expenses","Reallocate to participants"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Plan document rules case","Participant vesting ingestion case","Termination event control case","Forfeiture recognition case","Restoration obligation case"]})
]);
